LLM_URL = "http://localhost:1234/v1"
LLM_MODEL = "Qwen/Qwen2-7B-Instruct-GGUF"
LLM_MAX_TOKENS = 20000

LLM_TEXT2SQL_DOCS_RATIO = 0.5
LLM_TEXT2SQL_PROMPT_RATIO = 0.2
LLM_TEXT2SQL_HISTORY_RATIO = 0.3

LLM_DOCS_SELECTION_DCOS_RATIO = 0.8
LLM_DOCS_SELECTION_PROMPT_RATIO = 0.2


LLM_TEXT2SQL_DOCS_MAX_TOKENS = int(LLM_MAX_TOKENS * LLM_TEXT2SQL_DOCS_RATIO)
LLM_TEXT2SQL_PROMPT_MAX_TOKENS = int(LLM_MAX_TOKENS * LLM_TEXT2SQL_PROMPT_RATIO)
LLM_TEXT2SQL_HISTORY_MAX_TOKENS = int(LLM_MAX_TOKENS * LLM_TEXT2SQL_HISTORY_RATIO)

LLM_DOCS_SELECTION_DCOS_MAX_TOKENS = int(LLM_MAX_TOKENS * LLM_DOCS_SELECTION_DCOS_RATIO)
LLM_DOCS_SELECTION_PROMPT_MAX_TOKENS = int(
    LLM_MAX_TOKENS * LLM_DOCS_SELECTION_PROMPT_RATIO
)
